### ISSUE TITLE
not compatible with jquery/3.0.0

### ISSUE THREAD

**Issue by douglasdeodato** [mpryvkin/jquery-datatables-row-reordering#38]
Hi,

is this plugin still active?

i tried use today with jquery 3.0.0 and did not works,

the plugins works well with jquery 2.1

thank you.

**Comment by mpryvkin** [comment]
No, plug-in is not active and I'm not the original author, see [jQuery DataTables: Row reordering](http://www.gyrocode.com/articles/jquery-datatables-row-reordering/). 

I recommend using [RowReorder extension](http://datatables.net/extensions/rowreorder/) instead of this plug-in which only exists for backward compatibility with legacy code.
